<a href="https://colab.research.google.com/github/gaurav3010/Deep-Learning/blob/master/PyTorchIntro/PyTorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.4980, 0.1628],
        [0.3854, 0.7240],
        [0.1761, 0.0667]])


In [4]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[3.0141e-37, 0.0000e+00],
        [4.4842e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
x = torch.linspace(0, 1, steps=4)
print(x)

tensor([0.0000, 0.3333, 0.6667, 1.0000])


In [6]:
x = torch.tensor([[1, 2, 3],
                  [1, 2, 3],
                  [1, 2, 3]])
print(x)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


# Slicing Tensor

In [8]:
print(x.size())
print(x[:, 1])
print(x[1, :])

torch.Size([3, 3])
tensor([2, 2, 2])
tensor([1, 2, 3])


In [10]:
y = x[0, 0]
print(y)
print(y.item())

tensor(1)
1


# Reshaping Tensor

In [12]:
print(x)
y = x.view(9,-1)
print(y)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1],
        [2],
        [3],
        [1],
        [2],
        [3],
        [1],
        [2],
        [3]])


In [13]:
y = x.view(1, 9)
print(y)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3]])


# Simple Tensor Operation


In [19]:
x = torch.ones(3, 2)
y = torch.ones(3, 2)
print(x)
print(y)
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [21]:
z = y.add(x)
print(z)
print(y)
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# Numpy <-> Torch

In [22]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
a = np.random.rand(4)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[0.52902858 0.55684531 0.41205969 0.51671691]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([0.5290, 0.5568, 0.4121, 0.5167], dtype=torch.float64)


In [24]:
np.add(a, 1, out=a)
print(a)
print(a_pt)

[1.52902858 1.55684531 1.41205969 1.51671691]
tensor([1.5290, 1.5568, 1.4121, 1.5167], dtype=torch.float64)


In [25]:
%%time
for i in range(100):
  a = np.random.randn(100, 100)
  b = np.random.randn(100, 100)
  c = a + b

CPU times: user 101 ms, sys: 534 µs, total: 101 ms
Wall time: 107 ms


In [26]:
%%time
for i in range(100):
  a = torch.randn(100, 100)
  b = torch.randn(100, 100)
  c = a + b

CPU times: user 27.3 ms, sys: 969 µs, total: 28.2 ms
Wall time: 35.2 ms


# CUDA Support

In [2]:
print(torch.cuda.device_count())

1


In [4]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [0]:
cuda0 = torch.device('cuda:0')

In [6]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [7]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  c = a + b

CPU times: user 597 µs, sys: 6.42 ms, total: 7.02 ms
Wall time: 18.9 ms


In [8]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  torch.matmul(b, a)

CPU times: user 7.38 ms, sys: 9.33 ms, total: 16.7 ms
Wall time: 28 ms


# Autograd

In [9]:
x = torch.ones([3, 2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [12]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [13]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [16]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [21]:
x = torch.ones([3, 2], requires_grad=True)
print(x)
y = x + 5
print(y)
r = 1/(1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [24]:
x = torch.ones([3, 2], requires_grad=True)
print(x)
y = x + 5
print(y)
r = 1/(1 + torch.exp(-y))
#print(r)
a = torch.ones([3, 2])
r.backward(a)
print(x.grad)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


# Autograd example for W and B

In [0]:
x = torch.randn([20, 1], requires_grad=True)
y = 3*x - 2

In [0]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

y_hat = w*x + b

loss = torch.sum((y - y_hat) ** 2)

In [27]:
print(loss)

tensor(193.7740, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [29]:
print(w.grad, b.grad)

tensor([-39.9909]) tensor([102.5221])


# In loop

In [50]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

x = torch.randn([20, 1])
y = 3*x - 2

print(w.item(), b.item())

for i in range(10):
   
  y_hat = w*x + b
  loss = torch.sum((y_hat - y) ** 2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()
    
  print(w.item(), b.item())

tensor([[-2.2984],
        [-2.4699],
        [-1.8910],
        [-3.1442],
        [-1.9676],
        [-0.5311],
        [-8.4445],
        [-1.2444],
        [-3.3961],
        [-0.9535],
        [-5.5160],
        [ 1.1499],
        [ 0.7164],
        [-9.7105],
        [-3.8600],
        [-0.4073],
        [-4.0953],
        [ 0.5440],
        [-5.4417],
        [-4.7676]])
1.0 1.0
2.129746913909912 -0.43638336658477783
2.651851177215576 -1.164686679840088
2.8855159282684326 -1.539960265159607
2.9842612743377686 -1.7375072240829468
3.021385908126831 -1.8443645238876343
3.031491756439209 -1.9040911197662354
3.0306215286254883 -1.938732624053955
3.025994300842285 -1.9596203565597534
3.0206918716430664 -1.9726998805999756
3.0158987045288086 -1.981174349784851


# For large problem

In [86]:
%%time
learning_rate = 0.001
N = 10000
epochs = 2000

w = torch.rand([N], requires_grad=True)
b = torch.ones([1], requires_grad=True)

print(torch.mean(w).item(), b.item())
#print(y)

for i in range(epochs):
  
  x = torch.randn([N])
  y = torch.dot(3*torch.ones([N]), x) - 2

  y_hat = torch.dot(w, x) + b
  loss = torch.sum((y_hat - y) ** 2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()
      
  print(torch.mean(w).item(), b.item())

0.4998340308666229 1.0
0.5259767770767212 2.1505420207977295
0.532630205154419 2.832578420639038
0.5322040915489197 2.737633228302002
0.5320854187011719 2.7539069652557373
0.5353031754493713 3.02531361579895
0.5355969071388245 3.2192115783691406
0.5404160022735596 3.6635115146636963
0.539556086063385 3.543217182159424
0.541297972202301 4.009350776672363
0.5412961840629578 4.007083415985107
0.5410119891166687 3.749809741973877
0.5496048927307129 4.457931995391846
0.5499126315116882 4.300195693969727
0.5615192651748657 5.35943603515625
0.5675394535064697 4.821499824523926
0.5744653940200806 4.389849662780762
0.5735035538673401 3.4642415046691895
0.572498083114624 3.6398792266845703
0.5827848315238953 4.465290069580078
0.5880389213562012 3.767233371734619
0.6029108762741089 4.878754615783691
0.6047304272651672 5.268661975860596
0.6071263551712036 5.789462089538574
0.649880588054657 3.0192513465881348
0.6584944128990173 3.6648828983306885
0.669472336769104 4.194387912750244
0.6666312217712

In [87]:
%%time
learning_rate = 0.001
N = 10000
epochs = 2000

w = torch.rand([N], requires_grad=True, device=cuda0)
b = torch.ones([1], requires_grad=True, device=cuda0)

#print(torch.mean(w).item(), b.item())
#print(y)

for i in range(epochs):
  
  x = torch.randn([N], device=cuda0)
  y = torch.dot(3*torch.ones([N], device=cuda0), x) - 2

  y_hat = torch.dot(w, x) + b
  loss = torch.sum((y_hat - y) ** 2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()
      
  #print(torch.mean(w).item(), b.item())

CPU times: user 1.14 s, sys: 107 ms, total: 1.24 s
Wall time: 1.24 s
